[project]
authors = ["Sandra María Castro <scastro@eso.org>"]
channels = ["conda-forge"]
name = "testviper"
platforms = ["osx-arm64","linux-64"]
version = "0.0.1"
#platforms = ["linux-64"]

[dependencies]
python = ">=3.11,<3.14"
pytest = ">=8.4.0,<9"
python-casacore = "*"
numba = ">=0.57.0"
yamllint = "*"

[pypi-dependencies]
xradio = ">=0.0.56"
toolviper = ">=0.0.12"

[tasks]
test = "pytest -v -s tests/integration"


