[project]
authors = ["Sandra María Castro <scastro@eso.org>"]
channels = ["conda-forge"]
name = "testviper"
#platforms = ["osx-arm64"]
version = "0.0.1"
platforms = ["linux-64"]

[dependencies]
python = "3.13.*"
pytest = ">=8.4.0,<9"
python-casacore = "*"
yamllint = "*"

[pypi-dependencies]
xradio = ">=0.0.56"
toolviper = ">=0.0.12"

[tasks]
test = "pytest -v -s tests/integration"


