[project]
authors = ["Sandra María Castro <scastro@eso.org>"]
channels = ["conda-forge"]
name = "testviper"
platforms = ["osx-arm64","linux-64", "osx-64"]
version = "0.0.1"

[dependencies]
python = ">=3.11.0,<3.14"
pytest = ">=8.3.5,<9"
pytest-cov = ">=4.0.0,<5"
black = ">=23.0.0,<24"
isort = ">=5.0.0,<6"
python-casacore = ">=3.7.1,<4"
#toolviper = {git = "https://github.com/casangi/toolviper", branch = "main"}
#xradio = {git = "https://github.com/casangi/xradio", branch = "main"}

[pypi-dependencies]
toolviper = ">0.0.12"
xradio = ">=0.0.56"
