[pytest]
markers =
    integration: end-to-end tests requiring real data and compute
    timeout: per-test time limit in seconds

[tox]
envlist = latest, main

[testenv]
deps =
    -rrequirements/base.txt

[testenv:latest]
deps =
    -rrequirements/base.txt
    -rrequirements/latest.txt

[testenv:main]
deps =
    -rrequirements/base.txt
    -rrequirements/main.txt
