---
name: Integration Tests - Linux

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    name: >-
      Integration Tests on ${{ matrix.os }} /
      Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Clone component repositories
        run: |
          git clone https://github.com/casangi/toolviper.git
          git clone https://github.com/casangi/xradio.git
          git clone https://github.com/casangi/graphviper.git
          git clone https://github.com/casangi/astroviper.git

      - name: Install testviper dependencies
        run: pip install -r requirements/base.txt

      - name: Install components and their dependencies
        run: make build-main
#        run: pip install -r requirements/main.tx

      - name: Run testviper integration tests
        run: |
          pytest -v tests/integration/ --junitxml=testviper-test-results.xml
          ls -l

      - name: Run xradio tests
        run: |
          pytest -v ./xradio/tests/ --junitxml=xradio-test-results.xml
          ls -l

      - name: Run toolviper tests
        run: |
          pytest -v ./toolviper/tests/ --junitxml=toolviper-test-results.xml
          ls -l

      - name: Run graphviper tests
        run: |
          pytest -v ./graphviper/tests/ --junitxml=graphviper-test-results.xml
          ls -l

      - name: Run astroviper tests
        run: |
          pytest -v ./astroviper/tests/ --junitxml=astroviper-test-results.xml
          ls -l

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.python-version }}
          path: |
            testviper-test-results.xml
            xradio-test-results.xml
            toolviper-test-results.xml
            graphviper-test-results.xml
            astroviper-test-results.xml
          if-no-files-found: ignore

      - name: Setup Testspace
        uses: testspace-com/setup-testspace@v1
        with:
          domain: 'casangi' # Your Testspace organization subdomain

      - name: Publish to Testspace
        run: testspace *-test-results.xml