---
name: Integration Tests

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    name: >-
      Integration Tests on ${{ matrix.os }} /
      Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip dependencies (components)
        run: pip install -r requirements/main.txt

      - name: Install testviper dependencies
        run: pip install -r requirements/base.txt

      - name: Clone xradio repository
        run: git clone https://github.com/casangi/xradio.git

      - name: Run testviper integration tests
        run: |
          pytest -v tests/integration/ --junitxml=test-results.xml
          ls -l

      - name: Run xradio tests
        run: |
          pytest -v ./xradio/tests/ --junitxml=xradio-test-results.xml
          ls -l

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.python-version }}
          path: test-results.xml