---
name: Integration Tests

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    name: >-
      Integration Tests on ${{ matrix.os }} /
      Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip dependencies (components)
        run: |
          pip install git+https://github.com/casangi/toolviper.git@main
          pip install git+https://github.com/casangi/xradio.git@main
          pip install git+https://github.com/casangi/graphviper.git@main
          pip install git+https://github.com/casangi/astroviper.git@main

      - name: Install testviper dependencies
        run: pip install -r requirements/base.txt

      - name: Run integration tests
        run: |
          pytest -v tests --junitxml=test-results.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.xml
