---
name: Prefect Integration Tests on Branch - Linux

on:
  push:
    branches: ["*"]

jobs:
  test:
    name: >-
      Prefect Workflow Tests on ${{ matrix.os }} /
      Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
  
      - name: Install testviper dependencies and components
        run: |
          make build-main  #installs under external
          ls -l external
      - name: Install prefect dependencies and components
        run: |
          pip install prefect
          echo "prefect version:"
          prefect version
      - name: Install Allure CLI
        run: |
          wget -qO- https://nodejs.org/dist/v24.12.0/node-v24.12.0-linux-x64.tar.xz | tar -xJ
          export PATH=$HOME/node-v24.12.0-linux-x64/bin:$PATH
          npm install -g allure@3.1.0
          which allure
          echo "allure version:"
          allure --version
      - name: Create test results directories
        run: |
          mkdir -p testviper-tests/${{ matrix.python-version }}
          mkdir -p flowviper-tests/${{ matrix.python-version }}
          mkdir -p toolviper-tests/${{ matrix.python-version }}
          mkdir -p graphviper-tests/${{ matrix.python-version }}
          mkdir -p astroviper-tests/${{ matrix.python-version }}

      #- name: Run Prefect testviper integration tests
      #  run: |
      #    pytest -v tests/workflow/ \
      #    --junitxml="testviper-tests/${{ matrix.python-version }}/testviper-prefect-test-results-${{ matrix.python-version }}.xml" \
      #    --alluredir="testviper-tests/${{ matrix.python-version }}/allure-results"
      #    ls -l testviper-tests/${{ matrix.python-version }}/
      ## Checkout private flowviper repo and run tests
      - name: Checkout flowviper
        uses: actions/checkout@v4
        with:
          repository: 'casangi/flowviper'
          ref: '3-setup-flowviper-to-build-with-pyproject' # Temp branch for testing, change to main or default branch after testing
          path: 'flowviper' # Clones into $GITHUB_WORKSPACE/flowviper

      - name: Run build flowviper
        run: |
          cd flowviper
          pip install -e .
          ls -l flowviper
      - name: Run Prefect flowviper integration tests
        run: |
          pytest -v tests/integration/ \
          --junitxml="flowviper-tests/${{ matrix.python-version }}/flowviper-prefect-test-results-${{ matrix.python-version }}.xml" \
          --alluredir="flowviper-tests/${{ matrix.python-version }}/allure-results"
          ls -l flowviper-tests/${{ matrix.python-version }}/
      - name: Generate Test Summary
        if: always()
        uses: test-summary/action@v2
        with:
          paths: "/home/runner/work/testviper/testviper/**/**/${{ matrix.python-version }}/*-prefect-test-results-${{ matrix.python-version }}.xml"
      - name: Generate Allure Reports
        if: always()
        run: |
          #allure generate "testviper-tests/${{ matrix.python-version }}/allure-results" --output "testviper-tests/${{ matrix.python-version }}/allure-report"
          allure generate "flowviper-tests/${{ matrix.python-version }}/allure-results" --output "flowviper-tests/${{ matrix.python-version }}/allure-report"
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.python-version }}
          path: |
            test-results/*.xml
          if-no-files-found: ignore       
      #- name: Upload Allure Reports Testviper
      #  uses: actions/upload-artifact@v4
      #  if: always()
      #  with:
      #    name: allure-reports
      #    path: testviper-tests/${{ matrix.python-version }}/allure-report/
      #    retention-days: 30
      - name: Upload Allure Reports Flowviper
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-reports
          path: flowviper-tests/${{ matrix.python-version }}/allure-report/
          retention-days: 30
