---
name: Integration Tests with Allure Report

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install testviper dependencies
      run: |
        pwd
        ls -l
        make build-testviper
        
    - name: Clone component repositories
      run: |
        git clone https://github.com/casangi/toolviper.git
        git clone https://github.com/casangi/xradio.git
        git clone https://github.com/casangi/graphviper.git
        git clone https://github.com/casangi/astroviper.git
        ls -l
        
    - name: Install components
      run: |
        make build-main
        ls -l
        
    - name: Install Allure CLI
      run: |
        wget -qO- https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.tgz | tar -xz
        sudo mv allure-2.24.1 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
        
    - name: Checkout gh-pages-testing for history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages-testing
        path: gh-pages-testing
        
    - name: Copy Allure history
      if: always()
      continue-on-error: true
      run: |
        mkdir -p allure-results
        if [ -d "gh-pages-testing/allure-history" ]; then
          echo "Copying Allure history from previous runs"
          cp -r gh-pages-testing/allure-history allure-results/history
        else
          echo "No previous Allure history found"
        fi
        
    - name: Run tests and generate coverage
      run: |
        python scripts/test_runner_with_coverage.py
      
    - name: Generate Allure reports with history
      run: python scripts/enhanced_report_generator.py
      
    - name: Generate enhanced summary report with CodeCov links
      run: python scripts/enhanced_summary_generator.py
      
    - name: Upload Allure Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-reports
        path: allure-report/
        retention-days: 30
        
    - name: Deploy to gh-pages-testing
      uses: peaceiris/actions-gh-pages@v4
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-report
        publish_branch: gh-pages-testing
        force_orphan: false
