---
name: Integration Tests with Allure Report

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install testviper dependencies
      run: |
        pwd
        ls -l
        make build-testviper
        
    - name: Clone component repositories
      run: |
        git clone https://github.com/casangi/toolviper.git
        git clone https://github.com/casangi/xradio.git
        git clone https://github.com/casangi/graphviper.git
        git clone https://github.com/casangi/astroviper.git
        ls -l
        
    - name: Install components
      run: |
        make build-main
        ls -l
        
    - name: Install Allure CLI
      run: |
        wget -qO- https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.tgz | tar -xz
        sudo mv allure-2.24.1 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
        
    - name: Checkout gh-pages-staging for history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages-staging
        path: gh-pages-staging
        
    - name: Copy Allure history for each component
      if: always()
      continue-on-error: true
      run: |
        for comp in testviper toolviper xradio graphviper astroviper; do
          if [ -d "gh-pages-staging/main/allure-history/$comp" ]; then
            mkdir -p "allure-results-$comp/history"
            cp -r "gh-pages-staging/main/allure-history/$comp/." "allure-results-$comp/history/"
            echo "Copied history for $comp"
          else
            echo "No previous history for $comp"
          fi
        done
      
    # - name: Run tests and generate coverage
    #   run: |
    #     python scripts/test_runner_with_coverage.py
      
    - name: Generate Allure reports with history
      run: python scripts/enhanced_report_generator.py
      
    - name: Generate enhanced summary report with CodeCov links
      run: python scripts/enhanced_summary_generator.py
      
    - name: Upload Allure Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-reports
        path: allure-report/
        retention-days: 30
        
    - name: Deploy to gh-pages-staging
      uses: peaceiris/actions-gh-pages@v4
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-report
        publish_branch: gh-pages-staging
        destination_dir: main
        keep_files: true
        force_orphan: false
