---
name: Integration Tests with Allure Report

on:
  push:
    branches: ["**"]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
    - name: Install testviper dependencies
      run: |
        pwd
        make build-testviper
        
    - name: Clone component repositories
      run: |
        git clone https://github.com/casangi/toolviper.git
        git clone https://github.com/casangi/xradio.git
        git clone https://github.com/casangi/graphviper.git
        git clone https://github.com/casangi/astroviper.git
        ls -l
        
    - name: Install components
      run: |
        make build-main
        ls -l
        
    - name: Install Allure CLI
      run: |
        wget -qO- https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.tgz | tar -xz
        sudo mv allure-2.24.1 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
        
    - name: Checkout gh-pages for history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
        
    - name: Copy Allure history for each component
      if: always()
      continue-on-error: true
      run: |
        for comp in testviper toolviper xradio graphviper astroviper; do
          if [ -d "gh-pages/main/allure-history/$comp" ]; then
            mkdir -p "allure-results-$comp/history"
            cp -r "gh-pages/main/allure-history/$comp/." "allure-results-$comp/history/"
            echo "Copied history for $comp"
          else
            echo "No previous history for $comp"
          fi
        done
      
    # - name: Run tests and generate coverage
    #   run: |
    #     python scripts/test_runner_with_coverage.py

    - name: SetUp Grafana Alloy
      run: |
          export GCLOUD_HOSTED_METRICS_ID="2641355" 
          export GCLOUD_HOSTED_METRICS_URL="https://prometheus-prod-56-prod-us-east-2.grafana.net/api/prom/push" 
          export GCLOUD_HOSTED_LOGS_ID="1316354" 
          export GCLOUD_HOSTED_LOGS_URL="https://logs-prod-036.grafana.net/loki/api/v1/push" 
          export GCLOUD_FM_URL="https://fleet-management-prod-008.grafana.net" 
          export GCLOUD_FM_POLL_FREQUENCY="60s" 
          export GCLOUD_FM_HOSTED_ID="1358560" 
          export ARCH="amd64" 
          export GCLOUD_RW_API_KEY="${{ secrets.GCLOUD_RW_API_KEY }}"
          /bin/sh -c "$(curl -fsSL https://storage.googleapis.com/cloud-onboarding/alloy/scripts/install-linux.sh)"
          echo -e 'prometheus.remote_write "metrics_hosted_prometheus" {
              endpoint {
              name = "hosted-prometheus"
              url  = "https://prometheus-prod-56-prod-us-east-2.grafana.net/api/prom/push"
          
              basic_auth {
                username = "2641355"
                password = "${{ secrets.PROMETHEUS_REMOTE_PASSWORD }}"
              }
           }}' > /etc/alloy/config.alloy
          systemctl restart alloy.service
    #- name: Run tests and generate Allure reports with history
    #  run: python scripts/enhanced_report_generator.py
      
    #- name: Generate enhanced summary report with CodeCov links
    #  run: python scripts/enhanced_summary_generator.py
      
    #- name: Upload Allure Reports
    #  uses: actions/upload-artifact@v4
    #  if: always()
    #  with:
    #    name: allure-reports
    #    path: allure-report/
    #    retention-days: 30
        
    - name: Generate Test Summary
      uses: test-summary/action@v2
      with:
        paths: "/home/runner/work/testviper/testviper/tests/**/*-pytest-report.xml"
        
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-report
        publish_branch: gh-pages
        destination_dir: main
        keep_files: true
        force_orphan: false
