---
name: Integration Tests with Allure Report

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install testviper dependencies
      run: |
        pip install -r requirements/base.txt
        
    - name: Clone component repositories
      run: |
        git clone https://github.com/casangi/xradio.git
       
        
    - name: Install components
      run: |
        pip install -e "./xradio[all]"
        ls -l
        
    - name: Install Allure CLI
      run: |
        wget -qO- https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.tgz | tar -xz
        sudo mv allure-2.24.1 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
        
    - name: Run tests and generate coverage
      run: |
        mkdir -p allure-results
        pytest -v tests \
        --alluredir=allure-results \
        --cov=xradio \
        --cov-report=xml:coverage/coverage.xml \
        --cov-report=html:coverage/htmlcov \
        --cov-report=json:coverage/coverage.json
      
#    - name: Generate Allure reports
#      run: python scripts/report_generator.py
      
#    - name: Generate summary report
#      run: python scripts/summary_generator.py

    # Load test report history from gh-pages branch
    - name: Load test report history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages-staging
        path: gh-pages-staging
        
    # Build test report with history
    - name: Build test report with history
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        gh_pages: gh-pages-staging
        allure_report: allure-report
        allure_history: allure-history
      
    - name: Upload Allure Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-reports
        path: allure-report/
        retention-days: 30

    # Publish test report to GitHub Pages
    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v4
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages-staging
        publish_dir: allure-history
        
    # Optional: Post link to the report as a status check
    - name: Post the link to the report
      if: always()
      uses: Sibz/github-status-action@v1
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        context: 'Allure Test Report'
        state: 'success'
        sha: ${{ github.event.pull_request.head.sha || github.sha }}
        target_url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.run_number }}
        
