---
name: Integration Tests with Allure Report

on:
  push:
    branches: ["**"]
  workflow_dispatch:
    inputs:
      source_repository:
        description: 'Source repository that triggered the dispatch'
        required: false
        type: string
      source_ref:
        description: 'Source branch/ref that triggered the dispatch'
        required: false
        type: string
      source_sha:
        description: 'Source commit SHA that triggered the dispatch'
        required: false
        type: string
      source_actor:
        description: 'Source actor that triggered the dispatch'
        required: false
        type: string
      source_workflow:
        description: 'Source workflow that triggered the dispatch'
        required: false
        type: string
      source_run_id:
        description: 'Source run ID that triggered the dispatch'
        required: false
        type: string
      source_run_number:
        description: 'Source run number that triggered the dispatch'
        required: false
        type: string
      triggered_by:
        description: 'How this workflow was triggered'
        required: false
        type: string

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Log dispatch information
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "Workflow triggered by repository dispatch"
        echo "Source repository: ${{ github.event.inputs.source_repository }}"
        echo "Source ref: ${{ github.event.inputs.source_ref }}"
        echo "Source SHA: ${{ github.event.inputs.source_sha }}"
        echo "Source actor: ${{ github.event.inputs.source_actor }}"
        echo "Source workflow: ${{ github.event.inputs.source_workflow }}"
        echo "Source run ID: ${{ github.event.inputs.source_run_id }}"
        echo "Source run number: ${{ github.event.inputs.source_run_number }}"
        echo "Triggered by: ${{ github.event.inputs.triggered_by }}"
    
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
    - name: Install testviper dependencies
      run: |
        pwd
        make build-testviper
        
    - name: Clone component repositories
      run: |
        git clone https://github.com/casangi/toolviper.git
        git clone https://github.com/casangi/xradio.git
        git clone https://github.com/casangi/graphviper.git
        git clone https://github.com/casangi/astroviper.git
        ls -l
        
    - name: Install components
      run: |
        make build-main
        ls -l
        
    - name: Install Allure CLI
      run: |
        wget -qO- https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.tgz | tar -xz
        sudo mv allure-2.24.1 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
        
    - name: Checkout gh-pages for history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
        
    - name: Copy Allure history for each component
      if: always()
      continue-on-error: true
      run: |
        for comp in testviper toolviper xradio graphviper astroviper; do
          if [ -d "gh-pages/main/allure-history/$comp" ]; then
            mkdir -p "allure-results-$comp/history"
            cp -r "gh-pages/main/allure-history/$comp/." "allure-results-$comp/history/"
            echo "Copied history for $comp"
          else
            echo "No previous history for $comp"
          fi
        done
      
    # - name: Run tests and generate coverage
    #   run: |
    #     python scripts/test_runner_with_coverage.py
      
    - name: Run tests and generate Allure reports with history
      run: python scripts/enhanced_report_generator.py
      
    - name: Generate enhanced summary report with CodeCov links
      run: python scripts/enhanced_summary_generator.py
      
    - name: Upload Allure Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-reports
        path: allure-report/
        retention-days: 30
        
    - name: Generate Test Summary
      uses: test-summary/action@v2
      with:
        paths: "/home/runner/work/testviper/testviper/tests/**/*-pytest-report.xml"
        
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-report
        publish_branch: gh-pages
        destination_dir: main
        keep_files: true
        force_orphan: false
